import Head from 'next/head'
import Image from 'next/image'
import Accueil from '../components/Accueil'
import Deroule from '../components/Deroule'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import { DarkModeSwitch } from '../components/DarkModeSwitch';
import BurgerMenu from '../components/BurgerMenu'
import Section from '../components/Section'
import Nav from '../components/Nav'
export default function Home() {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Nav />
        <Accueil />
        <section className=''>
          <Section />
          </section>   
      </main>

      <Footer />

      
    </div>
  )
}
